version: '3.9'
networks:
  top-api-network:
    name: top-api-network
    driver: bridge

services:
  top-api-backend:
    image: top-api:latest
    container_name: top-api-backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - MONGO_LOGIN=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=top-api-mongo-db
      - MONGO_PORT=27017
      - MONGO_AUTH_DB=admin
      - JWT_SECRET=jwt
    depends_on:
      - top-api-mongo-db
    networks:
      - top-api-network

  top-api-mongo-db:
    image: mongo:latest
    container_name: top-api-mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27018:27017'
    volumes:
      - ./database/mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
    networks:
      - top-api-network
